const categories = [
  {
    id: 'animals-category',
    theme: 'Animals',
    list: [
      'bear',
      'rabbit',
      'fox',
      'wolf',
      'elephant',
      'panda',
      'tiger',
      'lion',
      'crocodile',
      'hedgehog',
      'cat',
      'dog',
      'hamster',
      'mouse',
      'dinosaur',
      'zebra',
      'squirrel',
      'moose',
      'deer',
      'goat',
      'lynx',
      'pig',
      'polar bear',
    ],
  },
  {
    id: 'tech-category',
    theme: 'Appliances',
    list: [
      'dishwasher',
      'fridge',
      'oven',
      'stove',
      'dryer',
      'computer',
      'printer',
      'iron',
      'toaster',
      'tv set',
      'washing machine',
      'mobile phone',
      'refrigerator',
      'coffee machine',
      'vacuum cleaner',
    ],
  },
  {
    id: 'birds-category',
    theme: 'Birds',
    list: [
      'sparrow',
      'swallow',
      'cuckoo',
      'pigeon',
      'crow',
      'swan',
      'duck',
      'eagle',
      'goose',
      'stork',
      'flamingo',
      'woodpecker',
    ],
  },
  {
    id: 'colors-category',
    theme: 'Colors',
    list: [
      'red',
      'blue',
      'green',
      'yellow',
      'white',
      'black',
      'orange',
      'brown',
      'pink',
      'gray',
    ],
  },
  {
    id: 'countries-category',
    theme: 'Countries',
    list: [
      'Estonia',
      'United States Of America',
      'Denmark',
      'Finland',
      'England',
      'Sweden',
      'Poland',
      'Netherlands',
      'Portugal',
      'Norway',
      'Austria',
      'Latvia',
      'Lithuania',
      'Belgium',
      'United Kingdom',
    ],
  },
  {
    id: 'fruits-category',
    theme: 'Fruits',
    list: [
      'orange',
      'pear',
      'apple',
      'tangerine',
      'mango',
      'lemon',
      'plum',
      'watermelon',
      'melon',
      'grapefruit',
      'aprikot',
      'nectarine',
      'peach',
    ],
  },
  {
    id: 'trees-category',
    theme: 'Trees',
    list: ['maple', 'spruce', 'birch', 'pine', 'alder', 'rowan', 'lilac'],
  },
];

export default categories;
